# Generated by Django 3.0.7 on 2020-08-16 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0010_website_category_and_defaults'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(help_text='Short descriptive name for this category.', max_length=200),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(help_text='Short descriptive unique name for use in urls.', max_length=255),
        ),
    ]
