# Generated by Django 2.2.4 on 2019-10-06 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0010_auto_20191002_0727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feed',
            name='image_url',
            field=models.URLField(blank=True, max_length=512, verbose_name='image_url'),
        ),
    ]
