# Generated by Django 2.2.4 on 2019-10-09 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0011_auto_20191006_2041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.CharField(blank=True, max_length=255, verbose_name='author'),
        ),
    ]
