# Generated by Django 2.2.4 on 2019-10-09 07:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0012_auto_20191009_0736'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taggedpost',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feeds.Post', verbose_name='post'),
        ),
        migrations.AlterField(
            model_name='taggedpost',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_tags', to='feeds.Tag', verbose_name='tag'),
        ),
    ]
