# Generated by Django 2.2.4 on 2019-10-12 08:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0013_auto_20191009_0759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enclosure',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enclosure', to='feeds.Post'),
        ),
    ]
