# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-04 17:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0002_website_commercial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(help_text='Short descriptive name for this category.', max_length=200, unique=True),
        ),
    ]
