# Generated by Django 2.1.4 on 2018-12-22 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0004_split_social_rating'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='website',
            options={'ordering': ('website_url',), 'verbose_name': 'website', 'verbose_name_plural': 'websites'},
        ),
        migrations.AddField(
            model_name='website',
            name='name',
            field=models.CharField(max_length=128, default=''),
        ),
    ]
