# Generated by Django 2.1.4 on 2018-12-30 14:44

from django.db import migrations, models


def split_website(apps, schema_editor):
    # We can't import the Person model directly as it may be a newer
    # version than this migration expects. We use the historical version.
    from urllib.parse import urlparse
    WebSite = apps.get_model('feeds', 'WebSite')
    for website in WebSite.objects.all():
        schema, netloc, path, params, query, fragment = \
            urlparse(website.website_url)
        website.schema = schema
        website.netloc = netloc
        website.path = path
        website.params = params
        website.query = query
        website.fragment = fragment
        website.save()


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0005_website_meta'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='website',
            options={
                'ordering': ('netloc',),
                'verbose_name': 'website',
                'verbose_name_plural': 'websites'
            },
        ),
        migrations.AddField(
            model_name='website',
            name='fragment',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='website',
            name='netloc',
            field=models.CharField(default='urllib.parse', max_length=512),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='website',
            name='params',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='website',
            name='path',
            field=models.CharField(default='/', max_length=512),
        ),
        migrations.AddField(
            model_name='website',
            name='query',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='website',
            name='scheme',
            field=models.CharField(choices=[
                ('http', 'HTTP'),
                ('https', 'HTTPS')
            ], default='https', max_length=5),
        ),
        migrations.AlterField(
            model_name='website',
            name='name',
            field=models.CharField(max_length=128),
        ),
        migrations.RunPython(split_website),
        migrations.RemoveField(
            model_name='website',
            name='website_url',
        ),
        migrations.AlterUniqueTogether(
            name='website',
            unique_together={('netloc', 'path')},
        ),
    ]
