# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-21 13:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0006_category_from_post'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.AlterField(
            model_name='feed',
            name='category',
            field=models.ManyToManyField(blank=True, related_name='category_feeds', to='category.Category'),
        ),
    ]
