# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-01 11:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0006_category_from_post'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enclosure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('href', models.URLField()),
                ('length', models.BigIntegerField()),
                ('enclosure_type', models.CharField(max_length=32)),
            ],
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.AlterField(
            model_name='feed',
            name='category',
            field=models.ManyToManyField(blank=True, related_name='category_feeds', to='category.Category'),
        ),
        migrations.AlterField(
            model_name='feed',
            name='slug',
            field=models.SlugField(blank=True, help_text='Short descriptive unique name for use in urls.', max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='filemodel',
            name='data',
            field=models.FileField(upload_to='', verbose_name='data'),
        ),
        migrations.AlterField(
            model_name='post',
            name='tags',
            field=models.ManyToManyField(related_name='tag_posts', through='feeds.TaggedPost', to='category.Tag'),
        ),
        migrations.AlterField(
            model_name='taggedpost',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_tags', to='category.Tag', verbose_name='tag'),
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
        migrations.AddField(
            model_name='enclosure',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enclosure', to='feeds.Post'),
        ),
    ]
