# Generated by Django 2.2.4 on 2019-12-24 08:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [('feeds', '0009_auto_20190927_0735'), ('feeds', '0010_auto_20191002_0727'), ('feeds', '0011_auto_20191006_2041'), ('feeds', '0012_auto_20191009_0736'), ('feeds', '0013_auto_20191009_0759'), ('feeds', '0014_auto_20191012_0850')]

    dependencies = [
        ('feeds', '0008_post_guidislink'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='content',
            new_name='summary',
        ),
        migrations.AlterField(
            model_name='feed',
            name='etag',
            field=models.CharField(blank=True, max_length=256, verbose_name='etag'),
        ),
        migrations.AlterField(
            model_name='feed',
            name='image_url',
            field=models.URLField(blank=True, max_length=512, verbose_name='image_url'),
        ),
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.CharField(blank=True, max_length=255, verbose_name='author'),
        ),
        migrations.AlterField(
            model_name='taggedpost',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feeds.Post', verbose_name='post'),
        ),
        migrations.AlterField(
            model_name='taggedpost',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_tags', to='feeds.Tag', verbose_name='tag'),
        ),
        migrations.AlterField(
            model_name='enclosure',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enclosure', to='feeds.Post'),
        ),
    ]
