# Generated by Django 3.0.2 on 2020-01-20 07:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0009_sqash_migrations_09_14'),
    ]

    operations = [
        migrations.AlterField(
            model_name='website',
            name='fragment',
            field=models.CharField(blank=True, default='', max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='website',
            name='name',
            field=models.CharField(default='', max_length=128),
        ),
        migrations.AlterField(
            model_name='website',
            name='params',
            field=models.CharField(blank=True, default='', max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='website',
            name='query',
            field=models.CharField(blank=True, default='', max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='website',
            name='slug',
            field=models.SlugField(default='', null=True),
        ),
        migrations.CreateModel(
            name='EditorCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Short descriptive name for this category.', max_length=200, unique=True)),
                ('slug', models.SlugField(help_text='Short descriptive unique name for use in urls.', max_length=255, unique=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='feeds.EditorCategory')),
            ],
            options={
                'verbose_name': 'editor_category',
                'verbose_name_plural': 'editor_categories',
                'ordering': ('name',),
                'unique_together': {('name', 'slug')},
            },
        ),
        migrations.AddField(
            model_name='website',
            name='category',
            field=models.ManyToManyField(default=None, related_name='website_category', to='feeds.EditorCategory'),
        ),
    ]
