# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-11 09:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0011_rename_website_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feed',
            name='website',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feeds', to='feeds.WebSite'),
        ),
    ]
