# Generated by Django 3.1.2 on 2021-01-09 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0013_summary_null'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='summary',
            field=models.TextField(blank=True, null=True, verbose_name='summary'),
        ),
    ]
