# Generated by Django 3.0.2 on 2020-01-20 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0010_auto_20191224_0842'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='editorcategory',
            options={'ordering': ('name',), 'verbose_name': 'editor_category', 'verbose_name_plural': 'editor_categories'},
        ),
        migrations.AlterField(
            model_name='website',
            name='category',
            field=models.ManyToManyField(default=None, related_name='website_category', to='feeds.EditorCategory'),
        ),
        migrations.AlterField(
            model_name='website',
            name='fragment',
            field=models.CharField(blank=True, default='', max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='website',
            name='params',
            field=models.CharField(blank=True, default='', max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='website',
            name='query',
            field=models.CharField(blank=True, default='', max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='website',
            name='slug',
            field=models.SlugField(default='', null=True),
        ),
    ]
